databases:
  - name: mikol-db
    plan: free
    databaseName: mikol
    user: mikol

services:
  - type: web
    name: mikol
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mikol-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
